### ISSUE TITLE
Скласти інтро

### ISSUE THREAD

**Issue by Ant-C-tech** [Ant-C-tech/homepage#4]
Скласти інтро (вступ), де в 2-4 реченнях описати, що замовник робить, що подобається робити, що хочеться робити краще, що важливо робити, тощо.

**Comment by Anton-Chyvikov** [comment]
I like it!

**Comment by Ant-C-tech** [comment]
I am happy with your comment!

**Comment by Anton-Chyvikov** [comment]
I'm an detail-oriented Software Engineer (Front-end / JavaScript) who seeking an entry-level position with Company to use my skills in coding, troubleshooting complex problems, and assisting in the timely completion of projects. I am inviting You to get acquainted with my skills and pet projects. Feel free!

**Comment by Ant-C-tech** [comment]
I am happy with your comment!
