### ISSUE TITLE
Скласти блок контактної інформації

### ISSUE THREAD

**Issue by Ant-C-tech** [Ant-C-tech/homepage#5]
Посилання на соцмережі (Facebook чи Instagram, тощо), номер телефону чи адреса електронної скриньки, тощо. Може не всі лінки в світі, а тільки ті, що дійсно доречні.

**Comment by Anton-Chyvikov** [comment]
Very good plan! Do it!

**Comment by Ant-C-tech** [comment]
I knew it was geneous!

**Comment by Anton-Chyvikov** [comment]
Contacts
E: chivikovanton@gmail.com
C: +38 098 910 34 41

**Comment by Ant-C-tech** [comment]
Thank You for this information!
