### ISSUE TITLE
Скласти таймлайн

### ISSUE THREAD

**Issue by Ant-C-tech** [Ant-C-tech/homepage#6]
Скласти список всіх (важливих) життєвих подій, визначних дат, досягнень, періодів, що дали приємний і неприємний досвід, тощо. В цьому конкретному випадку довгих списків не буває, натомість бувають погано згорнуті, тому пакуємо сюди все підряд, а про "лишні" події можна буде промовчати пізніше. Список повинен бути систематизованим і посортованим в такий спосіб, щоб читач швидко зрозумів "паттерн" і міг легко орієнтуватись в просторі і часі цього резюме.

**Comment by Anton-Chyvikov** [comment]
I am very excited about this!

**Comment by Ant-C-tech** [comment]
It is time to do it!

**Comment by Anton-Chyvikov** [comment]
*Higher Education*

State Higher Educational Institution Donbass State Teachers' Training University (DSTTU)
Physics teacher
September 2000 - June 2005 | Ukraine

*Work Experience*

PJSC “KZTS”
Lead engineer
3-D modeling (Solid Works), development of design documentation and related calculations and textual documentation for the production of machines and assemblies.
October 2013 - April 2020 | Ukraine

PC “Engineering center "Koks-Complex”
Second category engineer
May 2010 - December 2012 | Ukraine

PJSC "KB Koksokhimmash"
Second category engineer
December 2008 - May 2010 | Ukraine

Ukrprommash Group
Engineer, Second category engineer
June 2005 - November 2008 | Ukraine

*Web Development Education*

Kottans
Kottans Frontend 2021
November 2020 - Present | Ukraine
Course contents and results

Educational Programme “IT nation”
Advanced Front-End Web Developer
April 2020 - September 2020 | Ukraine

**Comment by Ant-C-tech** [comment]
It is time to do it!
