### ISSUE TITLE
Скласти додаткові інформаційні блоки

### ISSUE THREAD

**Issue by Ant-C-tech** [Ant-C-tech/homepage#7]
Можна зробити резюме менш формальним, додавши додаткові блоки, які містять корисну інформацію, але подають її в "розважальній" формі. Наприклад, що подобається і не подобається, сильні і слабкі сторони, перелік навиків чи хобі, інфографіка або ж інтерактивні модулі, тощо. Варто написати контент такого блоку раніше, ніж починати верстку, бо його розміри впливатимуть на розміщення елементів на сторінці.

**Comment by Anton-Chyvikov** [comment]
Don't hesitate to do that this way!

**Comment by Ant-C-tech** [comment]
Let's go!

**Comment by Anton-Chyvikov** [comment]
**Tech Skills**

Adobe Photoshop, Adobe XD,
Avocode, Figma, Zeplin
Git (Gitlab/ GitHub)

npm
Webpack
HTML5

CSS3
LESS
SCSS
Bootstrap
BEM Methodology

JavaScript ES6+
jQuery
React

Firebase
REST API

**English**
B1

**Comment by Ant-C-tech** [comment]
Let's go!
